---

- name: Dockutil | Ensure installed.
  homebrew:
    name: "dockutil"
    state: present

- name: Dockutil | Get information on items to remove
  shell: dockutil --find "{{ item }}"
  register: dockutil_removeditems
  with_items: "{{ dockitems_disabled }}"
  changed_when: false
  failed_when: false

- name: Dockutil | Remove all unwanted dock items
  shell: dockutil --remove "{{ item.item }}"
  when: '"{{ item.item }} was found in persistent-apps" in item.stdout'
  with_items:
    - "{{ dockutil_removeditems.results }}"

- name: Dockutil | Get information on configured setup
  shell: dockutil --find "{{ item.name }}"
  register: dockutil_newdata
  with_items: "{{ dockitems_enabled }}"
  changed_when: false
  failed_when: false

- name: Dockutil | Adding items
  shell: dockutil --add "{{ item.item.path }}"
  when: '"{{ item.item.name }} was not found" in item.stdout'
  with_items: "{{ dockutil_newdata.results }}"

- name: Dockutil | Get information on current setup
  shell: "dockutil --find '{{ item.name }}'"
  register: dockutil_currdata
  with_items: "{{ dockitems_enabled }}"
  changed_when: false
  failed_when: false

- name: Dockutil | Moving items
  shell: dockutil --move "{{ item.item.name }}" --position "{{ item.item.pos }}"
  with_items: "{{ dockutil_newdata.results }}"
  when:
  - '"{{ item.item.name }} was found in persistent-apps at slot {{ item.item.pos }} in" not in item.stdout'
