---

- name: Dockutil | Ensure installed.
  homebrew:
    name: "dockutil"
    state: present

- name: Dockutil | Get information on items to remove
  shell: dockutil --find "{{ item }}"
  register: dockutil_removeditems
  with_items: "{{ dockitems_disabled }}"
  changed_when: false
  failed_when: false

- name: Dockutil | Remove all unwanted dock items
  shell: dockutil --remove "{{ item }}"
  when: '"{{ item }} was found in persistent-apps at slot" in dockutil_removeditems.results'
  with_items:
    - "{{ dockitems_disabled }}"

- name: Dockutil | Get information on configured setup
  shell: dockutil --find "{{ item.name }}"
  register: dockutil_newdata
  with_items: "{{ dockitems_enabled }}"
  changed_when: false
  failed_when: false

- name: Dockutil | Adding items
  shell: dockutil --add "{{ item.path }}"
  when: '"{{ item.name }} was not found" in dockutil_newdata.results'
  with_items: "{{ dockitems_enabled }}"

- name: Dockutil | Moving items
  shell: dockutil --move "{{ item.name }}" --position "{{ item.pos }}"
  with_items: "{{ dockitems_enabled }}"
  when: '"{{ item.name }} was found in persistent-apps at slot {{ item.pos }} in" not in dockutil_newdata.results'

- name: Debug!
  debug:
    msg: '"{{ item.name }} was found in persistent-apps at slot {{ item.pos }} in" not in dockutil_newdata.results'
  with_items: "{{ dockitems_enabled }}"
  when: item.name == "TeamViewer"
