---
# handlers file for fubarhouse.macdock

- name: clear cache
  become: yes
  become_user: root
  shell: "{{ item }}"
  with_items:
    - 'find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \; | true'
    - 'find /private/var/folders/ -name com.apple.dock.iconcache -exec rm -rf {} \; | true'
    - 'rm -rf /Library/Caches/com.apple.iconservices.store | true'

- name: restart dock
  shell: "/usr/bin/killall Dock"
  failed_when: false
